// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mWVl6soqtg3VNXhMRhOtLMe-6Mxxw7s',
    appId: '1:437264632138:web:6bf2e404584bc58b9fd9b3',
    messagingSenderId: '437264632138',
    projectId: 'cv-viewer-8ac82',
    authDomain: 'cv-viewer-8ac82.firebaseapp.com',
    storageBucket: 'cv-viewer-8ac82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB25YM6hH7U2xVRJ1g6UukwFGHhg3nPYRM',
    appId: '1:437264632138:android:fde2c40122cd0da69fd9b3',
    messagingSenderId: '437264632138',
    projectId: 'cv-viewer-8ac82',
    storageBucket: 'cv-viewer-8ac82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2zT-R4RtAxuPLaLVsvviw4DmznkdKWQ',
    appId: '1:437264632138:ios:ab52e20ec3c7e4af9fd9b3',
    messagingSenderId: '437264632138',
    projectId: 'cv-viewer-8ac82',
    storageBucket: 'cv-viewer-8ac82.appspot.com',
    iosClientId: '437264632138-nvcrqrvr9e11l381di8d7hdscskg71ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT2zT-R4RtAxuPLaLVsvviw4DmznkdKWQ',
    appId: '1:437264632138:ios:997c67fe0c5138719fd9b3',
    messagingSenderId: '437264632138',
    projectId: 'cv-viewer-8ac82',
    storageBucket: 'cv-viewer-8ac82.appspot.com',
    iosClientId: '437264632138-27alhuuuo27oea2l9fbqecj0urbo1e09.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvViewer.RunnerTests',
  );
}
